[project]
name = "personal-finance-backend"
version = "0.1.0"
description = "Personal finance Django API"
requires-python = ">=3.12"
dependencies = [
    "annotated-types==0.7.0",
    "asgiref==3.11.0",
    "Django==6.0",
    "django-cors-headers==4.9.0",
    "djangorestframework==3.16.1",
    "djangorestframework-simplejwt==5.5.1",
    "pillow==12.1.1",
    "psycopg2-binary==2.9.11",
    "pydantic==2.12.5",
    "pydantic-settings>=2.7,<3",
    "pydantic-core==2.41.5",
    "PyJWT==2.10.1",
    "python-dotenv==1.2.1",
    "sqlparse==0.5.5",
    "typing-inspection==0.4.2",
    "typing-extensions==4.15.0",
    "tzdata==2025.3",
    "django-storages>=1.14.6",
    "boto3>=1.43.77",
]

[build-system]
requires = ["hatchling>=1.26.0"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["financeproject", "users"]
