# Generated by Django 6.0 on 2026-03-01 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='SpendTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_spend', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('starting_date', models.DateTimeField()),
                ('tracker_type', models.CharField(choices=[('month', 'Month'), ('week', 'Week'), ('year', 'Year')], max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('classification_data', models.JSONField(default=dict)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spend_trackers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('customer', 'tracker_type', 'starting_date')},
            },
        ),
    ]
