# Generated by Django 6.0 on 2026-03-01 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_receipt_last_updated_spendtracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='customer',
        ),
        migrations.DeleteModel(
            name='MonthlySpend',
        ),
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
