# Generated by Django 6.0 on 2026-03-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_summary_customer_delete_monthlyspend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spendtracker',
            name='receipts',
            field=models.ManyToManyField(blank=True, related_name='spend_trackers', to='users.receipt'),
        ),
    ]
