# Generated by Django 6.0 on 2026-03-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_spendtracker_receipts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='image_id',
        ),
        migrations.AddField(
            model_name='receipt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='image_processed',
            field=models.BooleanField(default=False),
        ),
    ]
