"""
Django settings for financeproject project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

from financeproject.app_settings import APP_SETTINGS

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = APP_SETTINGS.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

def _comma_separated_list(raw: str) -> list[str]:
    return [part.strip() for part in raw.split(",") if part.strip()]


ALLOWED_HOSTS = _comma_separated_list(APP_SETTINGS.BACKEND_ALLOWED_HOSTS)

_cors_env = APP_SETTINGS.CORS_ALLOWED_ORIGINS.strip()
if _cors_env:
    _browser_origins = _comma_separated_list(_cors_env)

CORS_ALLOWED_ORIGINS = _browser_origins
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = list(_browser_origins)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third-party
    "rest_framework",
    "corsheaders",
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'rest_framework.authtoken',
    "storages",

    # local
    "users",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'financeproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'financeproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # },
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": APP_SETTINGS.DB_NAME,
        "USER": APP_SETTINGS.DB_USER,
        "PASSWORD": APP_SETTINGS.DB_PASSWORD,
        "HOST": APP_SETTINGS.DB_HOST,
        "PORT": APP_SETTINGS.DB_PORT,
    }
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

_s3_ready = all(
    (
        APP_SETTINGS.S3_ACCESS_KEY_ID,
        APP_SETTINGS.S3_SECRET_ACCESS_KEY,
        APP_SETTINGS.S3_BUCKET_NAME,
        APP_SETTINGS.S3_REGION_NAME,
        APP_SETTINGS.S3_ENDPOINT_URL,
    )
)
if _s3_ready:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "access_key": APP_SETTINGS.S3_ACCESS_KEY_ID,
                "secret_key": APP_SETTINGS.S3_SECRET_ACCESS_KEY,
                "bucket_name": APP_SETTINGS.S3_BUCKET_NAME,
                "region_name": APP_SETTINGS.S3_REGION_NAME,
                "endpoint_url": APP_SETTINGS.S3_ENDPOINT_URL,
                "addressing_style": "path",
                "signature_version": "s3v4",
                "file_overwrite": False,
                "querystring_auth": True,
                "default_acl": None,
            },
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(
        minutes=APP_SETTINGS.JWT_ACCESS_TOKEN_LIFETIME_MINUTES,
    ),
    'REFRESH_TOKEN_LIFETIME': timedelta(
        hours=APP_SETTINGS.JWT_REFRESH_TOKEN_LIFETIME_HOURS,
    ),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

AUTH_USER_MODEL = 'users.Customer'
